### ISSUE TITLE
Maya - Creators Settings for Enabling/Disabling particular types malfunction or missing completely

### ISSUE THREAD

**Issue by LiborBatek** [ynput/ayon-maya#349]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
User should be able to disable all instance creator types not just some, there is also malfunctioning one for `Render` instance creator even if disabled its still listed...

Here are the `Creator` types which cant be disabled/enabled because they lack the settings:

<img width="155" height="250" alt="Image" src="https://github.com/user-attachments/assets/2d827200-c1bd-4514-afe1-e597e1ef2aa3" />

## Expected Behavior
User should be able to disable all creator types completely not just some....

### Steps To Reproduce:

1) Navigate to `ayon-maya` settings / creators
2) Disable all available creators listed in the settings
3) Inspect in maya and Publish/Create tab for available/disabled aka hidden creators
4) Some Creators couldnt be hidden/disabled via settings

### Version
latest ayon-maya and core

### What platform were you running when you found the bug?
Windows

You can also provide any additional information relevant to the issue.

### Relevant log output:

```shell

```

**Comment by BigRoy** [comment]
This should've all been fixed here: https://github.com/ynput/ayon-maya/pull/322

Which also got approved at the time.

**Comment by LiborBatek** [comment]
@BigRoy I have tested in the latest `ayon-maya` and its not working...not every creator even having a setting in addon but also `render` been present but not working

So its still an issue.
